import f1Capa from './f1-25.jpg.jpg';

export interface Genre {
  id: number;
  name: string;
}

export interface Game {
  id: number;
  name: string;
  released: string;
  background_image: string;
  rating: number;
  metacritic: number;
  playtime: number;
  description: string;
  genres: Genre[];
}

export interface RawgResponse<T> {
  count: number;
  results: T[];
}

export const mockGamesData: RawgResponse<Game> = {
  count: 20,
  results: [
    {
      id: 730,
      name: 'Counter-Strike 2',
      released: '2023-09-27',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/capsule_616x353.jpg',
      rating: 4.8,
      metacritic: 86,
      playtime: 450,
      description: 'O clássico FPS tático competitivo da Valve. Com a engine Source 2, apresenta gráficos reformulados, fumaças volumétricas dinâmicas e o modo Premier com ranking mundial.',
      genres: [{ id: 1, name: 'FPS' }, { id: 2, name: 'Competitivo' }, { id: 3, name: 'Ação' }],
    },
    {
      id: 2950000,
      name: 'F1® 25: 2026 Season Edition',
      released: '2025-05-30',
      background_image: f1Capa,
      rating: 4.7,
      metacritic: 86,
      playtime: 95,
      description: 'O videogame oficial com a edição da temporada de 2026 da Fórmula 1. Inclui o novo grid com Hamilton na Ferrari, Bortoleto, novas equipes e a física reformulada EA SPORTS Dynamic Handling.',
      genres: [{ id: 4, name: 'Corrida' }, { id: 5, name: 'Simulação' }, { id: 6, name: 'Esportes' }],
    },
    {
      id: 570,
      name: 'Dota 2',
      released: '2013-07-09',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/capsule_616x353.jpg',
      rating: 4.6,
      metacritic: 90,
      playtime: 600,
      description: 'Um dos MOBAs mais jogados do planeta. Escolha entre mais de 120 heróis únicos e dispute batalhas estratégicas em equipe 5v5 para destruir o Ancestral inimigo.',
      genres: [{ id: 7, name: 'MOBA' }, { id: 8, name: 'Estratégia' }, { id: 3, name: 'Ação' }],
    },
    {
      id: 1172470,
      name: 'Apex Legends',
      released: '2020-11-05',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/capsule_616x353.jpg',
      rating: 4.4,
      metacritic: 88,
      playtime: 190,
      description: 'Battle Royale dinâmico com heróis lendários possuindo habilidades poderosas. Jogue em esquadrões táticos nos confins das Terras Ermas.',
      genres: [{ id: 9, name: 'Battle Royale' }, { id: 1, name: 'FPS' }, { id: 3, name: 'Ação' }],
    },
    {
      id: 578080,
      name: 'PUBG: BATTLEGROUNDS',
      released: '2017-12-21',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/capsule_616x353.jpg',
      rating: 4.2,
      metacritic: 86,
      playtime: 210,
      description: 'Pouse em locais estratégicos, saqueie armas e suprimentos e sobreviva para se tornar a última equipe em pé em intensas partidas de até 100 jogadores.',
      genres: [{ id: 9, name: 'Battle Royale' }, { id: 10, name: 'Sobrevivência' }, { id: 1, name: 'FPS' }],
    },
    {
      id: 1086940,
      name: "Baldur's Gate 3",
      released: '2023-08-03',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg',
      rating: 4.9,
      metacritic: 96,
      playtime: 160,
      description: 'Vencedor do Jogo do Ano (GOTY). Um RPG narrativo de última geração no universo de Dungeons & Dragons, onde cada escolha sua molda a irmandade e o destino do mundo.',
      genres: [{ id: 11, name: 'RPG' }, { id: 8, name: 'Estratégia' }, { id: 12, name: 'Aventura' }],
    },
    {
      id: 1245620,
      name: 'ELDEN RING',
      released: '2022-02-25',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg',
      rating: 4.9,
      metacritic: 96,
      playtime: 150,
      description: 'Obra-prima Soulslike da FromSoftware em parceria com George R.R. Martin. Levante-se, Maculado, e atravesse as Terras Intermédias para restaurar o Anel Prístino.',
      genres: [{ id: 11, name: 'RPG' }, { id: 3, name: 'Ação' }, { id: 13, name: 'Mundo Aberto' }],
    },
    {
      id: 1174180,
      name: 'Red Dead Redemption 2',
      released: '2019-12-05',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg',
      rating: 4.9,
      metacritic: 97,
      playtime: 140,
      description: 'A épica jornada de Arthur Morgan e a gangue Van der Linde pelo coração da América no início do século XX, com um dos mundos abertos mais detalhados da história dos games.',
      genres: [{ id: 3, name: 'Ação' }, { id: 12, name: 'Aventura' }, { id: 13, name: 'Mundo Aberto' }],
    },
    {
      id: 271590,
      name: 'Grand Theft Auto V',
      released: '2015-04-14',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/capsule_616x353.jpg',
      rating: 4.7,
      metacritic: 97,
      playtime: 250,
      description: 'Explore o ensolarado e perigoso estado de San Andreas e viva a história entrelaçada de Michael, Franklin e Trevor, além do ecossistema massivo do GTA Online.',
      genres: [{ id: 3, name: 'Ação' }, { id: 13, name: 'Mundo Aberto' }],
    },
    {
      id: 252490,
      name: 'Rust',
      released: '2018-02-08',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/capsule_616x353.jpg',
      rating: 4.5,
      metacritic: 79,
      playtime: 320,
      description: 'O único objetivo no Rust é sobreviver. Supere a fome, a sede e o frio, construa sua base fortificada e proteja seus recursos de outros jogadores impiedosos.',
      genres: [{ id: 10, name: 'Sobrevivência' }, { id: 3, name: 'Ação' }, { id: 13, name: 'Mundo Aberto' }],
    },
    {
      id: 292030,
      name: 'The Witcher 3: Wild Hunt',
      released: '2015-05-18',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/capsule_616x353.jpg',
      rating: 4.8,
      metacritic: 93,
      playtime: 120,
      description: 'Você é Geralt de Rívia, caçador de monstros mercenário em um continente devastado pela guerra. Encontre Ciri, a Criança da Profecia, antes da Caçada Selvagem.',
      genres: [{ id: 11, name: 'RPG' }, { id: 3, name: 'Ação' }, { id: 13, name: 'Mundo Aberto' }],
    },
    {
      id: 1091500,
      name: 'Cyberpunk 2077',
      released: '2020-12-10',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg',
      rating: 4.5,
      metacritic: 86,
      playtime: 95,
      description: 'Um RPG de ação e aventura em mundo aberto ambientado em Night City, uma megalópole obcecada por poder, glamour e modificações corporais cibernéticas.',
      genres: [{ id: 11, name: 'RPG' }, { id: 1, name: 'FPS' }, { id: 13, name: 'Mundo Aberto' }],
    },
    {
      id: 553850,
      name: 'HELLDIVERS™ 2',
      released: '2024-02-08',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/553850/capsule_616x353.jpg',
      rating: 4.6,
      metacritic: 82,
      playtime: 85,
      description: 'A última linha de ataque da Galáxia. Junte-se aos Helldivers em esquadrões de até quatro amigos e lute pela Liberdade contra insetos e robôs alienígenas.',
      genres: [{ id: 3, name: 'Ação' }, { id: 1, name: 'FPS' }, { id: 14, name: 'Co-op' }],
    },
    {
      id: 2357570,
      name: 'Black Myth: Wukong',
      released: '2024-08-20',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2357570/capsule_616x353.jpg',
      rating: 4.8,
      metacritic: 81,
      playtime: 60,
      description: 'Um RPG de ação enraizado na mitologia chinesa baseado em Jornada ao Oeste. Como o Predestinado, enfrente seres míticos empunhando seu cajado e magias ancestrais.',
      genres: [{ id: 3, name: 'Ação' }, { id: 11, name: 'RPG' }],
    },
    {
      id: 2195250,
      name: 'EA SPORTS FC™ 24',
      released: '2023-09-29',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2195250/capsule_616x353.jpg',
      rating: 4.0,
      metacritic: 76,
      playtime: 180,
      description: 'A mais recente era do Jogo de Todo Mundo. Inclui a tecnologia HyperMotionV, PlayStyles otimizados pela Opta e o icônico modo Ultimate Team.',
      genres: [{ id: 6, name: 'Esportes' }, { id: 5, name: 'Simulação' }],
    },
    {
      id: 359550,
      name: "Tom Clancy's Rainbow Six Siege",
      released: '2015-12-01',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/359550/capsule_616x353.jpg',
      rating: 4.4,
      metacritic: 79,
      playtime: 290,
      description: 'Domine a arte da destruição e do uso de dispositivos em combates táticos em curta distância, planejamento estratégico de equipe e ambientes altamente destrutíveis.',
      genres: [{ id: 1, name: 'FPS' }, { id: 2, name: 'Competitivo' }, { id: 3, name: 'Ação' }],
    },
    {
      id: 413150,
      name: 'Stardew Valley',
      released: '2016-02-26',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/capsule_616x353.jpg',
      rating: 4.9,
      metacritic: 89,
      playtime: 110,
      description: 'Você herdou o antigo lote de fazenda do seu avô em Stardew Valley. Aprenda a viver da terra, faça amizades com os moradores da vila e construa uma nova vida próspera.',
      genres: [{ id: 15, name: 'Casual' }, { id: 5, name: 'Simulação' }, { id: 11, name: 'RPG' }],
    },
    {
      id: 105600,
      name: 'Terraria',
      released: '2011-05-16',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/capsule_616x353.jpg',
      rating: 4.9,
      metacritic: 83,
      playtime: 145,
      description: 'Cave, lute, explore e construa! O mundo é a sua tela e o chão a sua tinta em uma das maiores aventuras 2D com centenas de chefes, armas e segredos.',
      genres: [{ id: 10, name: 'Sobrevivência' }, { id: 12, name: 'Aventura' }, { id: 11, name: 'RPG' }],
    },
    {
      id: 227300,
      name: 'Euro Truck Simulator 2',
      released: '2012-10-18',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/capsule_616x353.jpg',
      rating: 4.8,
      metacritic: 79,
      playtime: 95,
      description: 'Viaje pela Europa como o rei da estrada, transportando cargas importantes através de dezenas de cidades da Inglaterra, Bélgica, Alemanha, Itália e muito mais.',
      genres: [{ id: 5, name: 'Simulação' }, { id: 4, name: 'Corrida' }],
    },
    {
      id: 620,
      name: 'Portal 2',
      released: '2011-04-18',
      background_image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/620/capsule_616x353.jpg',
      rating: 4.9,
      metacritic: 95,
      playtime: 20,
      description: 'A aclamada sequência do jogo inovador de quebra-cabeças com portais da Valve. Apresenta uma história solo hilária com GLaDOS e Wheatley e um modo cooperativo completo.',
      genres: [{ id: 16, name: 'Puzzle' }, { id: 12, name: 'Aventura' }],
    },
  ],
};